### ISSUE TITLE
Clase 4 - 11 SEP

### ISSUE THREAD

**Issue by AlejandroEB89** [CodeSystem2022/ERROR404-LABORATORIO4-PROGRAMACION4-JAVASCRIPT#7]
Subir Clase 4 - Lunes 11 Septiembre - Clase 04 E-commerce Básico Parte 04
Dev: Brian Ahumada
Scrum: Pablo Sanguinetti

**Comment by brianahumada** [comment]
Esta clase la subi la otra semana, la vuelvo a subir.
